backend:
  name: azure
  repo: glasswall/1GW/public-documentation
  branch: pb/fix_decap_cms
  tenant_id: 7049e6a3-141d-463a-836b-1ba40d3ff653
  app_id: f637ae8c-d020-4055-8f0d-2ed4bd86b169

publish_mode: simple
site_url: https://docs.glasswall.dev
display_url: https://docs.glasswall.dev
show_preview_links: false
media_folder: "/.attachments/"
public_folder: "/.attachments"
collections:
  - name: "docs"
    label: "docs"
    folder: docs-site
    create: true
    extension: 'md'
    summary: "{{dirname}}/{{filename}}.{{extension}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - { label: "Sidebar position", name: "sidebar_position", widget: number, value_type: int, required: false }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
    nested:
      depth: 10
      subfolders: false
      summary: '{{slug}}'
    meta: { path: { label: 'Path', widget: string } }
    sortable_fields: ['commit_date', 'title', 'commit_author', 'sidebar_position']
